### ISSUE TITLE
Finalize API for 1.0

### ISSUE THREAD

**Issue by Laremere** [googleforgames/open-match#1101]
We should finalize what our API surface that will be given a backwards compatible guarantee is, and ensure everything is ready.  Ideally we'll finalize everything in 0.10, and nothing will change.  However I don't want to absolutely rule out the possibility of any changes.  Just want to say "we think this is it, everyone please double check."

Things that I'm less sure about:
- Naming of evaluator and match function services - the other services had "Service" appended to the name.  Should we be consistent?
- Assignment is the only mutable field on ticket, and isn't populated in most places.  The only place it is populated is on a get ticket call.  I think we should move assignment to another field on the response from get ticket.
- I'm unsure about practical use of http/json.  While I don't see it going anywhere in the near term, I would like to exclude it from backward compatibility for the time being.
- https://github.com/googleforgames/open-match/issues/1100
- Error handling for FetchMatches in the case where we have some matches to return but an error has also happened.  We should decide on an API change, if any, that will be made and do it sooner rather than later.

@yfei1 @sawagh  @calebatwd Does anyone have another other items here?

**Comment by sawagh** [comment]
This is a good list to discuss - There are others API changes covered already as issues marked as v0.10. I would prefer to front-load any known API changes in v0.10 - so let us discuss the ones you listed here in the TSC meeting. 

Based on the discussion, the ones we consider can be separated out into issues of their own.

**Comment by sawagh** [comment]
I prefer breaking this issue into separate issues as required so we can discuss each of them on their merits. Here are my thoughts:

**Naming of evaluator and match function services - the other services had "Service" appended to the name. Should we be consistent?**
Lets create an issue for this - I am not very particular about this - but if this is internal only, we can also prioritize this after v0.10

**Assignment is the only mutable field on ticket, and isn't populated in most places. The only place it is populated is on a get ticket call. I think we should move assignment to another field on the response from get ticket.**
Already an issue for this - see resolution on the issue. 

**I'm unsure about practical use of http/json. While I don't see it going anywhere in the near term, I would like to exclude it from backward compatibility for the time being.**
We either test http/json support in 1.0 timeframe or do not claim to support it. I am OK not claiming to support it. However, I would prefer not to undo any work already done for this. Rather just creating an issue for v1.0 to say, validate http/json support would be sufficient - and if that issue is not prioritized for v1.0, then this scenario is not supported.

**#1100 Error handling for FetchMatches in the case where we have some matches to return but an error has also happened.**
Issue already present - lets discuss on that.

**Comment by sawagh** [comment]
Removing TSC discuss as we brought it up in TSC - issues already existing related to this were discussed - and as we create new specific issues from this that need TSC discussion , we can tag them accordingly.

**Comment by Laremere** [comment]
Ok, any issues which we think need to be resolved before we lock in backwards compatibility have been filed, so closing this issue.
