### ISSUE TITLE
Built-in "created" fields for tickets

### ISSUE THREAD

**Issue by calebatwd** [googleforgames/open-match#1113]
**Is your feature request related to a problem? Please describe.**
Having entity-level timestamps for tracking, tracing, and debugging tickets is really handy. Bonus points if we can use them in queries as a built-in index. e.g. "Give me all tickets that are older than 60 seconds"

**Describe the solution you'd like**
Add a concept for built-in indexes... the first one being a `created` timestamp in unix ms.

**Describe alternatives you've considered**
It IS possible that a user can totally fabricate this themselves... but it seems like an easy candidate for promotion to becoming an internally "automatic" feature of using tickets in open match.

**Comment by sawagh** [comment]
Thanks for filing this. We did have an issue to bring back meta indexes but eventually dropped it as no one asked for it. Do agree this will be useful and yes, even though this can be externally injected, if everyone may need it, might as well have this. 

In earlier discussions, we had heard concerns around someone may want to have a custom time there based on when the player started waiting in the game's queue (which may be different from create ticket time) but I think if someone needs that, they can always ignore the auto field and use their own. 

May be having it as a double SearchFields as opposed to a new field would give indexing / filtering for free. Of-course we need to auto-delete the index field once ticket vanishes (implementation detail)

**Comment by Laremere** [comment]
Multiple options, depending on the mixture these choices:
- Use int64, double, or google.protobuf.Timestamp
- Use a special field on ticket, a special field on search fields, or a well known search field value.
- Determining if the field can be filtered on or not.

For the type, I think we should definitely go with Timestamp.  It's specific, and languages have tooling for correctly turning it into native time types.  Eg: https://godoc.org/github.com/golang/protobuf/ptypes#Timestamp

I think that would be good for avoiding time related programming errors, eg messing up timezones.

As for where, adding a timestamp_args field with a special value is certainly doable, but feels off to me.

Adding it as a field to SearchFields would make sense if it is able to be used for filtering,
```protobuf
message SearchFields {
  // ...existing fields ...
  google.protobuf.Any create_time = 4;
}
```
Would be consistent with it being all the fields for filtering being on the SearchFields.
On the other hand, it wouldn't be something that could be set before creation (right?), so it feels better on the ticket, eg:

```protobuf
message Ticket {
  // ...existing fields ...
  google.protobuf.Any create_time = 6;
}
```  

When it comes to trying to add something to Pool is where there's more conflict in the design.

If there's timestamp_args added to the search fields, it's easy enough to add a range filter:
```protobuf 
message TimestampRangeFilter {
  // Name of the ticket's search_fields.timestamp_args this Filter operates on.
  string timestamp_arg = 1;

  // If present, the given timestamp must occur before this timestmap.
  google.protobuf.Any before = 2;

  // If present, the given timestamp must occur after this timestmap.
  google.protobuf.Any after = 3;
}
```

If the field is a special value, the before and after can just as easily be added to the pool:
```protobuf
message Pool {
  // ... existing fields ...
  
  // If present, the ticket must have been created before this timestmap.
  google.protobuf.Any created_before = 2;

  // If present, the ticket must have been created after this timestmap.
  google.protobuf.Any created_after = 3;
}
```

My biggest concern, for which I don't see a clear answer:
At some point, it's entirely reasonable that we'll add some compound filters.  Such as a range filter which expands based on the age of the ticket.  However we would want that filter to both work with the creation timestamp, and also with custom defined timestamps.  As such, the filters would get weird.

We could use one-ofs, to say either a timestamp_arg OR creation, but that starts to get messy.  Alternatively, we could define it as creation_time if you don't set the field arg, but that's starting to give some special behavior.  The special behavior doesn't seem avoidable.  Either we add a SearchField for you, or you have special behavior to filter a field which isn't in the SearchFields.

If we have this field, it definitely makes sense to add some special behavior within OM for it.  Eg, adding metrics based on ticket age percentiles for current in the pool and when tickets get matched.  For those operations, it feel weird to look into SearchFields. 

So that's what I see as the option space for this feature?  @sawagh and @calebatwd do you have any favorites, or options you'd like to rule out?

**Comment by yfei1** [comment]
My two cents:

1. For the type, if we expect the creation timestamp to work as expected for both gRPC and HTTP endpoints then `google.protobuf.Timestamp` is the only option. I remember the gRPC-gateway plugin has some restrictions or unexpected behavior if we define an int64 type and wanna convert it to JSON format without using Timestamp type.
2. For the SearchFields and Ticket args, would it make sense to have a special filter type just for the built-in values? Any subtype of the special filter type will only operate on a special map if we are down for the query cache approach or a "HSET" if we stick to indexing with Redis.
3. +1 for a filterable `created` timestamp. IMO this is the biggest value-added if we plan to support a built-in `created` type.

**Comment by sawagh** [comment]
+1 to both your thoughts on using google.protobuf.Timestamp. Also, I think there is a lot of value in making this field filterable (might simplify the wait time for users getting started) . It does not stop someone from creating their own - but I think it may be sufficient for common cases (also - it is clearly ticket creation time - not player queue time - so if you want the later - use something custom).

I do agree with @Laremere that from API perspective, it feels more natural to be on the Ticket. This is a read-only Ticket metadata that Open Match controls. On similar lines, I do prefer then, the first class created_before / created_after fields on Pool. Pairing the create_time on ticket and before/after on Pool seems conceptually clean. 

I do see your concern with compounded filters. My take is, if we keep this out of filters, hopefully we dont mix filter concepts with this. I still see the behavior question when we do filter expansions - but at that point, we can always deprecate this. (I doubt we ll get to compound expandable filters for 1.0)

@calebatwd - please chime in with your thoughts - may be we can close this one before the TSC meeting :)

**Comment by sawagh** [comment]
Based on the discussion, picking the parts of the original proposal that seem like a reasonable choice:

Have create_time on the Ticket:
message Ticket {
  // ...existing fields ...
  google.protobuf.Timestamp create_time = 6;
}

Have created_before / created_after fields on Pool. 

message Pool {
  // ... existing fields ...
  
  // If present, the ticket must have been created before this timestmap.
  google.protobuf.Timestamp created_before = 2;

  // If present, the ticket must have been created after this timestmap.
  google.protobuf.Timestamp created_after = 3;
}

**Comment by sawagh** [comment]
https://github.com/googleforgames/open-match/pull/1162
