### ISSUE TITLE
Reduce DNS queries.

### ISSUE THREAD

**Issue by axot** [googleforgames/open-match#1187]
In example code, it access svc FQDN using [om-backend.open-match.svc.cluster.local:50505](https://github.com/googleforgames/open-match/blob/master/examples/demo/components/director/director.go#L71)

It is better to add a trailing dot to reduce DNS queries.
For example `om-backend.open-match.svc.cluster.local.:50505`

**Comment by syntxerror** [comment]
Searched the repo for instances where the FQDN is not followed by the trailing dot ([for context](https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html)), it's only in helm, so I recommend adding it there to help out. For the tutorials this likely isn't high priority as well since we don't expect it to be long lived.
