### ISSUE TITLE
Move public API protos to pkg/pb/ directory.

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#122]
As our APIs stabilize and we want to start exposing them to be consumed publically we'll need a directory that indicates "safe to depend on". Typically this is the pkg/ directory for golang applications as stated by [golang-standards/project-layout/pkg](https://github.com/golang-standards/project-layout/tree/master/pkg). The official golang website does not have an opinion on this but using a well understood pattern I think is a reasonable fallback here.

At this point it's unclear when we'll reach that state but we should at least discuss and maybe put a doc.go file there to reserve the package for those changes. At the very latest it should be done populated once we start pushing v1.0.0 release candidates.

Some examples of stuff that should go into pkg/.
 1. Publicly consumable protocol buffer definitions like frontend.proto.
 1. Useful libraries that can be used to extend Open Match.
 1. The Go implementation of the gRPC harness.

**Comment by joeholley** [comment]
I think all of the current gRPC APIs and their messages - obviously excluding the Function/MatchFunction proto that's not merged yet - are publicly consumable, so would belong in here.  There was also a discussion about going ahead and implementing this sooner rather than later and having multiple directories with versioning in them, which I think could be valuable (basically, the way kubernetes.io does it with `k8s.io/***/v1` or `k8s.io/*****/v1alpha1` etc).  That would let us move to proper structure and pattern sooner rather than later.

**Comment by jeremyje** [comment]
That might end up being true but I think we'll want to audit the protos to see which are public. 
For API versioning I don't think we should give any API contract guarantee until we hit 1.0 otherwise we'll have to compromise major design changes based on decisions that were made while open match was not mature. 

A simpler approach to API versioning is to just have a v1 API and only make additive changes to it that way we can evolve it without maintaining multiple API versions which adds significant burden as the diverge. 

Generally I think [golang compatibility promise](https://golang.org/doc/go1compat) is a good model for this.

**Comment by yfei1** [comment]
I can take this.
