### ISSUE TITLE
Odd loglines from om-backend when using custom extension fields

### ISSUE THREAD

**Issue by luna-duclos** [googleforgames/open-match#1226]
**What happened**: We're using the extensions field on matches to store various types of custom data around our roster config, matchmaking settings, etc. Everything works, but om-backend contains some strange loglines looking like this:

```
Failed to obtain reader, failed to marshal fields to JSON, json: error calling MarshalJSON for type *grpc_logrus.jsonpbMarshalleble: jsonpb serializer failed: unknown message type "matchmaker.RosterConfig"
```

These lines are repeated for every type we have in the extensions and for each match we create, often several times.

**What you expected to happen**: om-backend logs things properly without spurious errors

**How to reproduce it (as minimally and precisely as possible)**: Have a matchfunction that creates matches using the extension fields

**Anything else we need to know?**: Don't think so

**Output of `kubectl version`**:

```
╰─ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: GKE

**Open Match Release Version**: 0.10.0

**Install Method(yaml/helm):**: helm

**Comment by Laremere** [comment]
I suspect what is happening is that it is trying to log RPC messages, and it does so by turning the protobuf into json.  Since the extension protos aren't compiled in with Open Match, it doesn't know how to turn the protos into json.

Possible resolutions I can think of right now:
- Turn off the logging that is causing these errors (to investigate: what precisely is the source of the errors, does it happen even without the logs turned on?)
- Build OM with the extension protos available.
- Find some other way to inform OM about the content of the extension protos.  (I think I read something about supporting arbitrary protos with the new Go proto library, something to look into?)
- Find a way to log only what the binary knows how to turn into text, and leave the rest out, or in a form which can be turned into the proto (base64 which could be decoded...)

**Comment by luna-duclos** [comment]
Another potential suggestion: Log matches but skip extension fields when logging

**Comment by aLekSer** [comment]
Working on this issue, will comment on this when I done investigation.

**Comment by syntxerror** [comment]
@aLekSer any progress on this from your investigation?

**Comment by mridulji** [comment]
Hi @luna-duclos, could you share the structure/definition of the custom data that you are trying to store in extensions field?

**Comment by mridulji** [comment]
Closing due to no response/ staleness.

@luna-duclos Please re-open if needed or you may use above suggestions for troubleshooting.
