### ISSUE TITLE
Support installing more than one Open Match instances in the same namespace

### ISSUE THREAD

**Issue by lihaif** [googleforgames/open-match#1235]
**What happened**:
We want to include Open Match as a sub-chart of our Meta-game helm chart.

In our CI Kubernetes cluster, we deploy all pipelines(each pipeline corresponds to a Meta-game helm deployment) to the same "CI" namespace and run auto-test based on each corresponding Meta-game cluster. The release name of each pipeline looks like "{pipeline-id}-{hash-code}", which will be used as the prefix of "fullname" in the resources of our helm chart. And we are able to deploy multiple Meta-game instances in the same namespace.

But I find that Open Match does not support to install multiple instances in the same namespace. e.g. the name of https://github.com/googleforgames/open-match/blob/57e59c3821b3eade27570ba5ea56c1c33caaaf4a/install/helm/open-match/templates/podsecuritypolicy.yaml#L21 is hard coded. We can not change it easily.

Another issue is that the "Release Name" is not part of the Open Match resource name, which makes it difficult to visually identify which release it belongs to if there are multiple releases in the same namespace.

**What you expected to happen**:
One possible solution is to include the "Release Name" as part of the resource name. For example. below is the code for MongoDB helm chart to get the "mongodb.fullname".

```
{{- define "mongodb.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}
```
Then each resource will use the "fullname" as their name. Then it will have different name for each release, which should solve the issue we have now.

**How to reproduce it (as minimally and precisely as possible)**:
Firstly release a Open Match cluster in "open-match" namespace
```
$ helm upgrade --install release1 --namespace open-match open-match/open-match
```
Then try to do another release in the same namespace. It reports error because there is resource with same name already exists.
```
$ helm upgrade --install release2 --namespace open-match open-match/open-match
```

**Anything else we need to know?**:

**Output of `kubectl version`**:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
(pythonvm)
```

**Cloud Provider/Platform (AKS, GKE, Minikube etc.)**: 
Minikube and Shared Kubenetes cluster for CI

**Open Match Release Version**:
1.0.0

**Install Method(yaml/helm):**:
helm

**Comment by lihaif** [comment]
Any comments on this issue? It's currently blocking our integration with Open Match.

**Comment by Laremere** [comment]
Hey,

PRs are welcome, though I suggest you start with a small description of how you would like to solve the problem with alternatives you considered.

However, I don't think this is really necessary, and would possibly add a bunch of complexity in a place where I'd really like there to be less complexity than there already is.  Assuming that you could install any number of OM instances in a single k8s namespace without any further work is something that I don't find intuitive.  Generally what I've seen when dealing with testing that requires a resource - in this case a namespace - the method of running the tests involves workers on a queue, or otherwise locking the resource.  If you were to do this, it would accomplish the same thing (avoiding conflict) without requiring additional complexity in OM.  If you need more due to throughput concerns, setting up a small number of namespaces would work.

In my experience running some very complicated integration tests, this locking mechanism worked well.  As a bonus your confusion about which resources are owned by which test run will be gone, which will also help make debugging easier as only one test will be running in a namespace at a time.

**Comment by lihaif** [comment]
Hi Scott,

Thanks for your input. I have opened a ticket to handle this in our next sprint. I will let you how we will deal with it.

**Comment by TBBle** [comment]
Note: I'm a colleague of @lihaif, so this is the same request, not a second use-case.

I find it surprising (counter-intuitive, in fact) for a Helm chart that isn't designed to be once-per-cluster, e.g. cert-manager or Agones, to have hard-coded resource names, and hence only be installable once-per-namespace.

No one on our team ever thought to check if this was a problem when evaluating Open Match; I certainly didn't because, amongst the dozen or so other Helm charts we use, nothing else has this behaviour.

If nothing else, [documenting this limitation](https://open-match.dev/site/docs/installation/helm/), and perhaps not using a replaceable-looking release name in the installation instructions would help. Why call it "my-release" if you can never install a second Open Match with another name in that namespace?

It also blocks usage when a team share a single namespace (which is the case on our of our k8s providers) as we'd be forever stumbling over each other's toes if we tried to share a single Open Match instance.

My preferred solution would be to have the chart work like most other Helm charts, and use the release name or similar (i.e the `fullname` macro in @lihaif's example) in all the resource names. For legacy reasons, `fullnameOverride` probably needs to be "om" by default, but I haven't looked super-hard at that.

It'd also be nice if the charts included the [Standard Labels](https://helm.sh/docs/chart_best_practices/labels/), which makes it much easier to select resources belong that to a particular Helm deployment without hunting through name-matching etc. But that is a separate issue.

Alternatively, a Cluster-wide OpenMatch, driven entirely by resources for things like "Where is my redis?" and "Where is my Evaluator?" would work. That's a pretty significant redesign though. We're used to that arrangement from Agones, and understand the benefits and tradeoffs there. I actually expected Open Match to work that way when I first heard about it.

**Comment by Laremere** [comment]
Hey,

Thanks for push back.  It's good to hear that your experience is different from my intuition.

I don't think making OM a once-a-cluster type thing makes any sense.  Mutli-tenant might help with your use case, but I see it as independent - especially if you're testing bringing up your entire stack.

I wouldn't worry about backwards compatibility for configuration - we specifically excluded it in the stability guarantees: https://github.com/googleforgames/open-match-docs/issues/169  We knew at the time of going 1.0 that things were likely to change when it comes to configuration, and I'd rather get things right.  Still good to avoid unnecessary churn though.

Do you have any references for the release name being part resource names as a standard in helm usage?

**Comment by TBBle** [comment]
It's done in both the Helm [example library helpers chart](https://github.com/helm/helm/tree/master/cmd/helm/testdata/testcharts/lib-chart#commonfullname), and is also the case when you [create a new Helm chart with `helm create`](https://github.com/helm/helm/blob/6a536661fcf1dc0315798ece70bbf193e725945c/pkg/chartutil/create.go#L396-L412). You can see that every "metadata.name:" in the created chart references "fullname", with or without a suffix.

The Open Match Helm chart contained the default `openmatch.fullname` template from initial creation in #81 until it was removed in #667, but the initial templates didn't use `openmatch.fullname` to name the resources.

#119 started overriding this behaviour in the redis sub-chart by [setting `redis.fullNameOverride`](https://github.com/googleforgames/open-match/commit/f3160cfc5ccb58e75c0c5f6be6d9a1a3d454758d#diff-2947309d8df955e363995909ee0939b5R63), to align it with the parent chart's not using the `openmatch.fullname` template.

So, it looks like the OM Helm chart has taken significant steps to override this default behaviour. I don't see any discussion about this, but the initial chart creation would have had to manually strip `openmatch.fullname` from the default-created templates.

**Comment by Laremere** [comment]
All great pointers, thanks.

I'm convinced this would be a positive change, if anyone wants to pursue making it.  I personally would like to take a deeper look at all of the helm stuff and see if things need reworking.  Created an issue for that: https://github.com/googleforgames/open-match/issues/1244
