### ISSUE TITLE
How exactly match conflict happens ?

### ISSUE THREAD

**Issue by Kiddinglife** [googleforgames/open-match#1301]
The document says:

> Case2 - Overlapping MatchProfiles
The Director could request for the following Profiles:

Profile1 has a Pool that filters all Tickets with mmr 0 to 5.
Profile2 has a Pool that filters all Tickets with mmr 2 to 8.
Profile3 has a Pool that filters all Tickets with mmr 6 to 10.
In this case, the MatchFunction executing Profile1 and Profile2 will have some common players they consider for generating Matches (Similarly with Profile2 and Profile3). Thus, the generated Matches may have overlapping Tickets.

Here if I only have **1 MatchFunction**, does it still have overlapping tickets ?

**Comment by HazWard** [comment]
Since the match function will be called concurrently with the 3 profiles you will still have overlapping tickets. The evaluator will take care of de-colliding the proposals made by the match function.

**Comment by Kiddinglife** [comment]
Thank you foryour reply.
I still have two questions:
1. Does the same thing happen on string equal filter and tag filter  ?
For example:  
Profile1 has a Pool that filters all Tickets with k1:v1 and k2:v2.
Profile2 has a Pool that filters all Tickets with k1:v1.
2. Say I I have only **1 Profile** that has two Pools - the first pool filters all Tickets withk1:v1 and k2:v2 and and the second pool filters all Tickets with k1:v1.
3. Does match conflic have relationship with the concurrency of  fetch matc hrequest ?
for example, 
Profile1 has a Pool that filters all Tickets with k1:v1 and k2:v2 and is used by request 1
Profile2 has a Pool that filters all Tickets with k1:v1 and is used by request 2

**Comment by syntxerror** [comment]
@Kiddinglife To answer your questions:

> Does the same thing happen on string equal filter and tag filter ?
For example:
Profile1 has a Pool that filters all Tickets with k1:v1 and k2:v2.
Profile2 has a Pool that filters all Tickets with k1:v1.

In this example, Profile 1 would have a subset of the tickets from Profile 2. There is no guarantee that any conflict will not happen here but there is a possibility.

> Will there be conflicts if I I have only 1 Profile that has two Pools - the first pool filters all Tickets withk1:v1 and k2:v2 and the second pool filters all Tickets with k1:v1 ?

If you have two pools with practically the same data then likely there won't be any conflicts if one match function run will likely create proposals using both pools. Conflict happens when proposals are created with tickets that have already been considered for a match.

> Does match conflicts have relationship with the concurrency of fetch match request ?
for example,
Profile1 has a Pool that filters all Tickets with k1:v1 and k2:v2 and is used by request 1
Profile2 has a Pool that filters all Tickets with k1:v1 and is used by request 2

Match conflicts happen with any match functions registered within the same registration interval with the synchronizer. If Profile 1 and Profile 2 are both registered within this window they can have conflicts. If not, then it's unlikely you'd find any.
