### ISSUE TITLE
How to resolve overlapping tickets  if multiple evaluators are deployed

### ISSUE THREAD

**Issue by jjchenlian** [googleforgames/open-match#1416]
If there are repeated matches, how does the evaluator expand horizontally？thanks

**Comment by jjchenlian** [comment]
If there are repeated matches, the evaluator can only be deployed at a single point?

**Comment by joeholley** [comment]
Since each running matchmaking function invocation does not know if it is selecting tickets that other invocations are also selecting, the evaluator is by design a single fan-in point. It is where all results of all matchmaking functions can be evaluated against each other.  In general, the scaling of the evaluator process is not necessary - if you think your evaluation process will take too long, it is best to take a different approach (either stop making profiles with overlapping pools, or optimize your evaluator code). Please see the [documentation for more information. ](https://open-match.dev/site/docs/guides/evaluator/)

**Comment by syntxerror** [comment]
@eda-yuji-10472 if a collision happens and they aren't evaluated together, that is the big red flag that likely would cause issues. If this approach is working for you, then by all means feel free to continue but we recommend optimizing your evaluator code to avoid these situations.
