### ISSUE TITLE
Rename Frontend, Backend, MMLogic API names

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#267]
Currently, Open Match exposes the following APIs: 

Frontend API: The API to which the players (or some component managing the players) connects
Backend API: The API to which the director or DGS can connect to request for matches
MMLogic API: The API exposed by Open Match to the MMF's / Evaluator to request for data. 

The 'Frontend' / 'Backend' names derive from - what components in an online game services setup connect to these APIs (Frontend API is the API to be connected by a game's frontend, Backend API to be connected to by a Game's backend).

However, these names are not intuitive - and also confusing (for example, the 'Backend' is really a 'Frontend' for the logic that triggers matchmaking / evaluation etc)

Starting the issue to brainstorm suggestions to make these names reflect what they actually do - than who calls them.

As starters for discussion, TicketManager, MatchFinder, DataAccess :) far from ideal but hoping to get better suggestions here!

**Comment by Laremere** [comment]
Not very fond of "DataAccess", all apis have data and you access them, so it's not very descriptive.
I like MMLogic, or something along those lines, as it specifies what it's used for.  I think it's reasonable in the future that there might be other APIs for the Match Maker Function that don't involve database access.

**Comment by joeholley** [comment]
I think one of the things to consider is that for many other (off-the-shelf and first-party) matchmaking solutions, initiating finding matches happens due to a _request from the game client_.  Open Match breaks with this pattern significantly, and to some degree it's probably helpful to try to name the APIs in a way that makes this obvious.  That's one of the reasons things got named the current way; anyone who doesn't read the instructions because they are familiar with other matchmakers and just 'dives in' will see pretty quickly that the API designated to be the frontend for clients doesn't provide any calls to initiate match logic.  Hopefully this limits how many people have a bad experience by unknowingly applying the traditional paradigm to OM. In fact, we've already seen multiple people come to the slack after seeing that CreateMatch is a Backend call to ask what they are supposed to do :)

That said: I'm not strongly attached to 'backend' as the name of the API, but if I put on my 'intermediate industry developer' hat - I'm going to assume that "MatchFinder" (or the like) is an API my game client should hit to initiate match logic.

**Comment by sawagh** [comment]
Tracked by https://github.com/googleforgames/open-match/issues/337
