### ISSUE TITLE
Investigate Alternatives to Redis

### ISSUE THREAD

**Issue by jeremyje** [googleforgames/open-match#350]
Redis is a fast datastore because it's basically shared memory with an RPC layer. Unfortunately,  Open Match requires a few queries that are challenging to implement on top of Redis and call into question if there are better alternatives.

We should look at other datastore solutions and determine which would be a good replacement for Redis.

**Comment by yfei1** [comment]
Some of the open match APIs expect our state store service to execute atomic transactions. For example, `backend.UpdateAssignments` function takes in a slice of ticket ids and would expect either all updates are successful, or nothing occurs because of some errors (e.g. ticket does not exist). Redis does use the term [transaction](https://redis.io/topics/transactions) in its documentation, yet per documentation:

> It's important to note that even when a command fails, all the other commands in the queue are processed – Redis will not stop the processing of commands.

So the `MULTI` -> `EXEC` pattern used around open match only guarantees all the commands are atomically in-queue for Redis. We should consider switching to a datastore with atomic behavior if a replacement is needed.

**Comment by sawagh** [comment]
We discussed several options over the past few months here. Here was the issue that came close: 
https://github.com/googleforgames/open-match/issues/1117

Currently, the option we are pursuing is a cache over redis than an alternative to it: 
https://github.com/googleforgames/open-match/issues/1123

At this point, I want to close this generic issue to investigate alternatives as it does not scope the work well. If we pursue specific alternatives, please create a separate issue to track those alternatives and we can discuss.

**Comment by Laremere** [comment]
Yes, but I wanted to close this issue....
