### ISSUE TITLE
Limit the data read when processing a Pool (set of filters)

### ISSUE THREAD

**Issue by yfei1** [googleforgames/open-match#401]
Some api calls in open match will return/query too much data from the storage service. I open this issue to track and discuss how to resolve this problem.

**Comment by sawagh** [comment]
When Open Match processes a set of filters, it queries data for each filter from state storage. Currently there are no limits to how much data gets fetched from state storage. So if a pool queries players over an entire range of index (say ranking min to max), that would attempt to pull the entire player population. We need to add limits to protect the system from such scenarios.

**Comment by sawagh** [comment]
Lets discuss this for v0.9 - This would be a change in behavior - so either we frontload this - or we can decide that the existing behavior is ok and that this should be addressed by best practices guidance.

**Comment by sawagh** [comment]
Does not look like we have a reasonable solution here. One of the common cases we hit this was with ever increasing pools due to failing partial match processing. This does get mitigated to some extent now that we make partial progress. Re-open if this is a strong ask - and we encounter this issue in real scenarios.
