### ISSUE TITLE
Garbage Collection / Cleanup of Tickets, Index, Ignore Lists etc.

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#682]
Some scenarios around ticket deletion need to cleanly garbage collect state in Redis:

Deleting a Ticket should cascade removal of entries from ignore lists, indexes (including any meta indexes). Removal of index property should clean up any tickets that were already indexed against that property. Do we need any expiration / garbage collection for Tickets with Assignments Remove Tickets from ignore list after they hit expiration ttl?

**Comment by yfei1** [comment]
Redis does not provide native support to set TTL for members in a sorted set. I come up with three ways to garbage collect the items in our IgnoreList but I feel like they would either involve some scalability concerns or add more complexities to our codebase.

Option1:
Redis has a `ZREMRANGE` command to remove ranged items in a sorted set. One of the options is to maintain a cron job or background job to handle the gc.

Option2:
Instead of having an extra tool to handle the gc, we can add a `ZREMRANGE` call to `synchronizer.Evaluate` or `backend.FetchMatches` method such that every API call to these methods triggers the gc.

**Comment by yfei1** [comment]
Hold off this change as #681 may change how the statestore works

**Comment by yfei1** [comment]
Closed by #830. Opened #815 to track the items left.
