### ISSUE TITLE
Consider Alternatives to existing Harness mechanism

### ISSUE THREAD

**Issue by sawagh** [googleforgames/open-match#685]
Currently, we have a harness that hydrates tickets - having the MMF to be a simple function call. However, that needs us to provide harness implementation in other languages so that an MMF can be implemented in other languages.

We have a couple options:

1. Incorporate harness functionality into OpenMatch backend. Always hydrate tickets. This may not be great in scenarios where MMF needs to make specific queries - may have redundant hydration queries.

2. Add a flag in the FetchMatches that indicates whether backend will hydrate the Tickets or not - that way, hydration can be opted in / out. 

3. Incorporate the harness into an example - that way, the current harness just becomes a part of golang example - anyone writing in golang and wanting hydration still has a working example (same as today) and just moving around the harness resets expectations around providing harness in other languages. It will be same as providing examples in other languages.

**Comment by calebatwd** [comment]
Option #2 is pretty nice, and doesn't necessarily complicate the function too much (the developer will need to write their function code to possibly handle ticket collections as input, or an empty collection if the responsibility is on the function to put the query together). Admittedly, the function authoring experience does simplify some of the backend does the hydration optionally.
The broader question of providing first-class harnesses vs providing samples is tough. In a lot of ways, a proto and any contract implementation someone wants to fill in feels like a reasonable barrier to step over for someone who wants to host this system, especially since it doesn't include "build" and some of the other features you might expect from a function hoster.

**Comment by sawagh** [comment]
We are deprecating the existing harness mechanism completely - so this issue as discussed is not directly relevant any more. If there is some additional harness work we identify from user use-cases, we can either take that on in OM Core - or in the Ecosystem repo.
